
# Generated by Django 5.1.6 on 2025-05-19 12:50


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuisine',
            old_name='cusine_name',
            new_name='cuisine_name',
        ),
    ]
