# Generated by Django 5.1.6 on 2025-05-21 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_ingredient'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredient',
            new_name='CheckboxIngredient',
        ),
    ]
